	LDA 2001 // LOAD THE ACCUMULATOR WITH VALUE AA
	MOV H,A // MOVE THE VALUE IN ACCUMULATOR TO REGISTER H
	LDA 2002 // LOAD THE ACCUMULATOR WITH VALUE AF
	ADD H // ADDS THE VALUE IN REGISTER H TO THE VALUE IN ACCUMULATOR A AND STORES THE RESULT IN A
	MOV L,A // MOVE THE VALUE IN ACCUMULATOR TO REGISTER L
	MVI A,00H // LOADS THE VALUE 00H INTO ACCUMULATOR
	ADC A // ADDS THE CONTENTS OF THE CARRY FLAG TO VALUE IN ACCUMULATOR
	MOV H,A // MOVE THE VALUE IN A TO THE H REGISTER
	SHLD 2003 // STORES THE VALUE S IN H AND L REGISTER AS (16 BIT) WORD IN MEMORY ADDRESS 2003
	HLT
#ORG 2001
#DB AAH,AFH
